///LoginAction Types///
export const LOGIIN_API = "LOGIIN_API";
export const LOGIIN_API_SUCCESS = "LOGIIN_API_SUCCESS";
export const LOGIIN_API_FAILURE = "LOGIIN_API_FAILURE";

//Logout types
export const LOGOUT = "LOGOUT";

///Admin Action Types///
export const GET_ADMINS = "GET_ADMINS";
export const GET_ADMINS_SUCCESS = "GET_ADMINS_SUCCESS";
export const GET_ADMINS_FAILURE = "GET_ADMINS_FAILURE";

export const RESET_ADMIN_STATE = "RESET_ADMIN_STATE";
export const ADMIN_SIGN_UP = "ADMIN_SIGN_UP";
export const ADMIN_SIGN_UP_SUCCESS = "ADMIN_SIGN_UP_SUCCESS";
export const ADMIN_SIGN_UP_FAILURE = "ADMIN_SIGN_UP_FAILURE";

export const UPDATE_ADMIN = "UPDATE_ADMIN";
export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS";
export const UPDATE_ADMIN_FAILURE = "UPDATE_ADMIN_FAILURE";

///University Action Types///
export const GET_UNIVERSITIES = "GET_UNIVERSITIES";
export const GET_UNIVERSITIES_SUCCESS = "GET_UNIVERSITIES_SUCCESS";
export const GET_UNIVERSITIES_FAILURE = "GET_UNIVERSITIES_FAILURE";

export const CREATE_UNIVERSITY = "CREATE_UNIVERSITY";
export const CREATE_UNIVERSITY_SUCCESS = "CREATE_UNIVERSITY_SUCCESS";
export const CREATE_UNIVERSITY_FAILURE = "CREATE_UNIVERSITY_FAILURE";

export const UPDATE_UNIVERSITY = "UPDATE_UNIVERSITY";
export const UPDATE_UNIVERSITY_SUCCESS = "UPDATE_UNIVERSITY_SUCCESS";
export const UPDATE_UNIVERSITY_FAILURE = "UPDATE_UNIVERSITY_FAILURE";

export const DELETE_UNIVERSITY = "DELETE_UNIVERSITY";
export const DELETE_UNIVERSITY_SUCCESS = "DELETE_UNIVERSITY_SUCCESS";
export const DELETE_UNIVERSITY_FAILURE = "DELETE_UNIVERSITY_FAILURE";

///College Action Types///
export const GET_COLLEGES = "GET_COLLEGES";
export const GET_COLLEGES_SUCCESS = "GET_COLLEGES_SUCCESS";
export const GET_COLLEGES_FAILURE = "GET_COLLEGES_FAILURE";

export const CREATE_COLLEGE = "CREATE_COLLEGE";
export const CREATE_COLLEGE_SUCCESS = "CREATE_COLLEGE_SUCCESS";
export const CREATE_COLLEGE_FAILURE = "CREATE_COLLEGE_FAILURE";

export const UPDATE_COLLEGE = "UPDATE_COLLEGE";
export const UPDATE_COLLEGE_SUCCESS = "UPDATE_COLLEGE_SUCCESS";
export const UPDATE_COLLEGE_FAILURE = "UPDATE_COLLEGE_FAILURE";

export const DELETE_COLLEGE = "DELETE_COLLEGE";
export const DELETE_COLLEGE_SUCCESS = "DELETE_COLLEGE_SUCCESS";
export const DELETE_COLLEGE_FAILURE = "DELETE_COLLEGE_FAILURE";

///School Action Types///
export const GET_SCHOOLS = "GET_SCHOOLS";
export const GET_SCHOOLS_SUCCESS = "GET_SCHOOLS_SUCCESS";
export const GET_SCHOOLS_FAILURE = "GET_SCHOOLS_FAILURE";

export const CREATE_SCHOOL = "CREATE_SCHOOL";
export const CREATE_SCHOOL_SUCCESS = "CREATE_SCHOOL_SUCCESS";
export const CREATE_SCHOOL_FAILURE = "CREATE_SCHOOL_FAILURE";

export const UPDATE_SCHOOL = "UPDATE_SCHOOL";
export const UPDATE_SCHOOL_SUCCESS = "UPDATE_SCHOOL_SUCCESS";
export const UPDATE_SCHOOL_FAILURE = "UPDATE_SCHOOL_FAILURE";

export const DELETE_SCHOOL = "DELETE_SCHOOL";
export const DELETE_SCHOOL_SUCCESS = "DELETE_SCHOOL_SUCCESS";
export const DELETE_SCHOOL_FAILURE = "DELETE_SCHOOL_FAILURE";

///Degree Action Types///
export const GET_DEGREES = "GET_DEGREES";
export const GET_DEGREES_SUCCESS = "GET_DEGREES_SUCCESS";
export const GET_DEGREES_FAILURE = "GET_DEGREES_FAILURE";

export const CREATE_DEGREE = "CREATE_DEGREE";
export const CREATE_DEGREE_SUCCESS = "CREATE_DEGREE_SUCCESS";
export const CREATE_DEGREE_FAILURE = "CREATE_DEGREE_FAILURE";

export const UPDATE_DEGREE = "UPDATE_DEGREE";
export const UPDATE_DEGREE_SUCCESS = "UPDATE_DEGREE_SUCCESS";
export const UPDATE_DEGREE_FAILURE = "UPDATE_DEGREE_FAILURE";

export const DELETE_DEGREE = "DELETE_DEGREE";
export const DELETE_DEGREE_SUCCESS = "DELETE_DEGREE_SUCCESS";
export const DELETE_DEGREE_FAILURE = "DELETE_DEGREE_FAILURE";

///Field Action Types///
export const GET_FIELDS = "GET_FIELDS";
export const GET_FIELDS_SUCCESS = "GET_FIELDS_SUCCESS";
export const GET_FIELDS_FAILURE = "GET_FIELDS_FAILURE";

export const CREATE_FIELD = "CREATE_FIELD";
export const CREATE_FIELD_SUCCESS = "CREATE_FIELD_SUCCESS";
export const CREATE_FIELD_FAILURE = "CREATE_FIELD_FAILURE";

export const UPDATE_FIELD = "UPDATE_FIELD";
export const UPDATE_FIELD_SUCCESS = "UPDATE_FIELD_SUCCESS";
export const UPDATE_FIELD_FAILURE = "UPDATE_FIELD_FAILURE";

export const DELETE_FIELD = "DELETE_FIELD";
export const DELETE_FIELD_SUCCESS = "DELETE_FIELD_SUCCESS";
export const DELETE_FIELD_FAILURE = "DELETE_FIELD_FAILURE";

///Subject Action Types///
export const GET_SUBJECTS = "GET_SUBJECTS";
export const GET_SUBJECTS_SUCCESS = "GET_SUBJECTS_SUCCESS";
export const GET_SUBJECTS_FAILURE = "GET_SUBJECTS_FAILURE";

export const CREATE_SUBJECT = "CREATE_SUBJECT";
export const CREATE_SUBJECT_SUCCESS = "CREATE_SUBJECT_SUCCESS";
export const CREATE_SUBJECT_FAILURE = "CREATE_SUBJECT_FAILURE";

export const UPDATE_SUBJECT = "UPDATE_SUBJECT";
export const UPDATE_SUBJECT_SUCCESS = "UPDATE_SUBJECT_SUCCESS";
export const UPDATE_SUBJECT_FAILURE = "UPDATE_SUBJECT_FAILURE";

export const DELETE_SUBJECT = "DELETE_SUBJECT";
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_FAILURE = "DELETE_SUBJECT_FAILURE";

///Career Action Types///
export const GET_CAREERS = "GET_CAREERS";
export const GET_CAREERS_SUCCESS = "GET_CAREERS_SUCCESS";
export const GET_CAREERS_FAILURE = "GET_CAREERS_FAILURE";

export const CREATE_CAREER = "CREATE_CAREER";
export const CREATE_CAREER_SUCCESS = "CREATE_CAREER_SUCCESS";
export const CREATE_CAREER_FAILURE = "CREATE_CAREER_FAILURE";

export const UPDATE_CAREER = "UPDATE_CAREER";
export const UPDATE_CAREER_SUCCESS = "UPDATE_CAREER_SUCCESS";
export const UPDATE_CAREER_FAILURE = "UPDATE_CAREER_FAILURE";

export const DELETE_CAREER = "DELETE_CAREER";
export const DELETE_CAREER_SUCCESS = "DELETE_CAREER_SUCCESS";
export const DELETE_CAREER_FAILURE = "DELETE_CAREER_FAILURE";

///Question Action Types///
export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAILURE = "GET_QUESTIONS_FAILURE";

export const CREATE_QUESTION = "CREATE_QUESTION";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_FAILURE = "CREATE_QUESTION_FAILURE";

export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_FAILURE = "UPDATE_QUESTION_FAILURE";

export const DELETE_QUESTION = "DELETE_QUESTION";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAILURE = "DELETE_QUESTION_FAILURE";